import { drizzle } from "drizzle-orm/mysql2";
import { subscriptionPlans } from "../drizzle/schema.ts";

const db = drizzle(process.env.DATABASE_URL);

const plans = [
  {
    name: "Free",
    tier: "free",
    priceMonthly: 0,
    priceYearly: 0,
    features: JSON.stringify([
      "Access to basic recipe collection",
      "5 AI chat messages per month",
      "Save up to 10 recipes",
      "Basic price comparison",
      "Shopping list"
    ]),
    maxAiMessages: 5,
    maxRecipeSaves: 10,
    hasPriceAlerts: false,
    hasMealPlanning: false,
    hasPdfExport: false,
    hasExclusiveRecipes: false,
  },
  {
    name: "Premium",
    tier: "premium",
    priceMonthly: 999, // $9.99/month
    priceYearly: 9900, // $99/year (2 months free)
    features: JSON.stringify([
      "Access to ALL recipes including premium exclusives",
      "Unlimited AI chat messages",
      "Unlimited recipe saves",
      "Advanced price tracking & alerts",
      "Meal planning calendar",
      "Export recipes to PDF",
      "Priority customer support",
      "Ad-free experience"
    ]),
    maxAiMessages: 0, // unlimited
    maxRecipeSaves: 0, // unlimited
    hasPriceAlerts: true,
    hasMealPlanning: true,
    hasPdfExport: true,
    hasExclusiveRecipes: true,
  },
  {
    name: "Pro",
    tier: "pro",
    priceMonthly: 1999, // $19.99/month
    priceYearly: 19900, // $199/year (2 months free)
    features: JSON.stringify([
      "Everything in Premium",
      "Advanced AI cooking assistant with personalized recommendations",
      "Custom meal plans generated by AI",
      "Nutritional analysis and tracking",
      "Shopping list auto-sync with supermarkets (coming soon)",
      "Recipe creation and sharing",
      "White-label meal planning for families",
      "API access for developers",
      "Dedicated account manager"
    ]),
    maxAiMessages: 0, // unlimited
    maxRecipeSaves: 0, // unlimited
    hasPriceAlerts: true,
    hasMealPlanning: true,
    hasPdfExport: true,
    hasExclusiveRecipes: true,
  },
];

async function seedPlans() {
  console.log("🌱 Seeding subscription plans...");
  
  try {
    await db.insert(subscriptionPlans).values(plans);
    console.log(`✅ Added ${plans.length} subscription plans`);
    console.log("🎉 Seeding complete!");
  } catch (error) {
    console.error("❌ Seeding failed:", error);
    process.exit(1);
  }
  
  process.exit(0);
}

seedPlans();
